### ISSUE TITLE
Schnitzeljagd: Device Status

### ISSUE THREAD

**Issue by Egomann88** [Egomann88/M335_Projektarbeit-Schnitzeljagd#6]
- [x] Page erstellt?
- [x] ~Berechtigungen?~
- [x] Zugriff auf Ladestand?
- [x] Getestet?

**Comment by Jyods** [comment]
[#909c613](https://github.com/Egomann88/M335_Projektarbeit-Schnitzeljagd/commit/909c61383fbc0e16e6e7bf2f66ca7e926dfdb794)
