### ISSUE TITLE
Schnitzeljagd: WLAN

### ISSUE THREAD

**Issue by Egomann88** [Egomann88/M335_Projektarbeit-Schnitzeljagd#7]
- [x] Page erstellt
- [ ] ~WLAN ID von ICT-KR4 speichern~
- [ ] ~Aktuelle WLAN ID mit ICT-KR4 vergleichen~
- [x] Getestet?

**Comment by Jyods** [comment]
[#dd1336b](https://github.com/Egomann88/M335_Projektarbeit-Schnitzeljagd/commit/dd1336b6ef346f62220260b028d136aac9fbc668)
